#!/usr/bin/python3

"""Create Coinboot Plugins

Usage:
  create_plugin start
  create_plugin finish <plugin-name>

Options:
  -h --help     Show this screen.

"""

import os
from docopt import docopt
from fnmatch import fnmatch
from subprocess import call

DPKG_STATUS = '/var/lib/dpkg/status'
INITIAL_DPKG_STATUS = '/tmp/initial_status'
FINAL_DPKG_STATUS = '/tmp/dpkg_status'


def main(arguments):
    #print(arguments)
    if arguments['start']:
         call(['cp', '-v', DPKG_STATUS, INITIAL_DPKG_STATUS])
    elif arguments['finish']:
         f = open(FINAL_DPKG_STATUS, 'w')
         call(['dpkg_status.py', '--old', 'INITIAL_DPKG_STATUS', '--new', 'DPKG_STATUS', '--diff'], stdout=f)

if __name__ == '__main__':
    arguments = docopt(__doc__, version='Crease Coinboot Plugins v0.1')
    main(arguments)


