sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install --yes fakeroot
  - wget https://github.com/frzb/coinboot-debirf/releases/download/20180923/coinboot-initramfs-4.4.0-133-generic -P /tmp

script:
  - ./coinbootmaker /tmp/coinboot-initramfs-4.4.0-133-generic
  - ls -la build
