sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install --yes fakeroot bridge-utils
  - wget https://github.com/frzb/coinboot-debirf/releases/download/20190116/coinboot-initramfs-4.15.0-43-generic -P /tmp

script:
  - >
    for plugin in $(basename src/*); do
    ./coinbootmaker /tmp/coinboot-initramfs-4.15.0-43-generic -p $plugin
    done
  - ls -la build

deploy:
  provider: releases
  api_key: ${TOKEN}
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    repo: frzb/coinboot-plugins
    branch: master
    tags: false
