#!/bin/bash

# Copyright (C) 2018 Gunter Miegel coinboot.io
#
# This file is part of Coinboot.
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

# Helper script to convert initramfs archive into a Docker container.

display_help() {
  echo
  echo 'Coinbootmaker creates an environment for building Coinboot plugins from an'
  echo 'given Coinboot Initramfs.'
  echo
  echo 'When no arguments beside the path to a Coinboot Initramfs is supplied'
  echo 'Coinbootmaker automatically builds all plugins from the ./src directory.'
  echo 'Packaged Coinboot pluings are written to the ./builds directory'
  echo
  echo 'Usage: coinbootmaker [-i] <path to initramfs>'
  echo
  echo '-i            Interactive mode - opens a shell in the build environment'
  echo '-h            Display this help'
  echo
}

while getopts "ih" opt; do
  case $opt in
    i)
      interactive=true
      ;;
    h)
      display_help
      exit 1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

shift $((OPTIND -1))

BASEDIR=$PWD
INITRAMFS=$1
WORKING_DIRECTORY=/tmp/$(basename $INITRAMFS)_extracted_by_-coinbootmaker

install -d cache
install -d build

mkdir -p $WORKING_DIRECTORY
cd $WORKING_DIRECTORY


zcat $INITRAMFS | fakeroot cpio -idm

# Now we extract the nested initramfs
# We force to overwrite existing files from busybox with '-u'
zcat rootfs.cgz | fakeroot cpio -uidm

# The nested initramfs archive can be removed now
echo $PWD
fakeroot rm -v rootfs.cgz

cd $BASEDIR

fakeroot tar -C $WORKING_DIRECTORY -c . | docker import - coinbootmaker

if ! grep -q '200000' /proc/sys/fs/inotify/max_user_watches; then
  echo 'Increasing number of file watches for inotify to 200000.'
  echo 'This requires sudo privileges'
  echo '200000' | sudo tee /proc/sys/fs/inotify/max_user_watches
fi

# We are affected by a race condition by the way how 'inotifywait'
# used in 'create_plugin' uses 'inotify' on recursive directories when
# not running on a superfast storage backend like RAMFS/TMPFS.
# Leading to random missing files while creating an plugin archive.
# There was a regression Docker < 18.02 ignoring
# the environment variable DOCKER_RAMDISK to be set.
# https://github.com/moby/moby/issues/36120

docker_version=$(docker info 2> /dev/null | grep "Server Version"|cut -d' ' -f 3)
docker_version_major=$(echo $docker_version | cut -d '.' -f 1)
docker_version_minor=$(echo $docker_version | cut -d '.' -f 2 | sed 's/^0//')

if  [ $docker_version_major -lt 18 ]; then
  echo "You are running Docker $docker_version"
  echo "You need at least Docker 18.02 with support for DOCKER_RAMDISK"
  exit 1
elif [ $docker_version_minor -lt 2 ]; then
  echo "You are running Docker $docker_version"
  echo "You need at least Docker 18.02 with support for DOCKER_RAMDISK"
  exit 1
fi

export DOCKER_RAMDISK=true


if [ ! -z $interactive ] && [ $interactive = 'true' ]; then
  docker run --rm -it -v "$PWD":/mnt coinbootmaker bash
else
  docker run --rm -it -v "$PWD":/mnt coinbootmaker bash -c 'cd /mnt/build/ && run-parts /mnt/src'
fi

echo "Cleaning up $WORKING_DIRECTORY"
rm -rf $WORKING_DIRECTORY

