#!/bin/bash -e

# Copyright (C) 2021 Gunter Miegel coinboot.io
#
# This file is part of Coinboot.
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.
#
# Please notice even while this script is licensed with the
# MIT license the software packaged by this script may be licensed by
# an other license with different terms and conditions.
# You have to agree to the license of the packaged software to use it.

# Download and install Team Red Miner

create_plugin.py start

TEAMREDMINER_RELASE=0.8.1.1
TEAMREDMINER_ARCHIVE=teamredminer-v$TEAMREDMINER_RELASE-linux.tar.gz
TEAMREDMINER_URL=https://github.com/todxx/teamredminer/releases/download/v$TEAMREDMINER_RELASE/$TEAMREDMINER_ARCHIVE
WGET='wget'

apt install $WGET --yes --no-install-recommends

if ! [ -f /tmp/$TEAMREDMINER_ARCHIVE ]; then
  wget --progress=bar:force \
   $TEAMREDMINER_URL -P /tmp
else
  echo "$TEAMREDMINER_ARCHIVE is already downloaded."
fi

if ! [ -f /tmp/$TEAMREDMINER_RELASE ]; then
  tar -zxvf /tmp/$TEAMREDMINER_ARCHIVE -C /tmp
else
  echo "$TEAMREDMINER_ARCHIVE is already decompressed."
fi

if ! [ -f "/usr/local/bin/teamredminer" ]; then
 cp -r "/tmp/bin/teamredminer" "/usr/local/bin/"
else
  echo "teamredminer $TEAMREDMINER_RELASE binary is already copied to the chroot."
fi

if ! [ -d "/usr/local/bin/kernels" ]; then
 cp -r "/tmp/bin/kernels" "/usr/local/bin/"
else
  echo "teamredminer $TEAMREDMINER_RELASE kernels are already copied to the chroot."
fi

cat <<'EOF' > "/etc/systemd/system/teamredminer.service"
[Unit]
Description=teamredminer Ethereum Minining Software
After=network-online.target

[Service]
EnvironmentFile=/etc/environment
ExecStart=/usr/local/bin/teamredminer -R --HWMON 1 -G \
-P stratum1+tcp://${ETHEREUM_ADDRESS}.%H@eu1.ethermine.org:4444 \
-P stratum1+tcp://${ETHEREUM_ADDRESS}.%H@eu1.ethermine.org:14444 \
-P stratum1+tcp://${ETHEREUM_ADDRESS}.%H@us1.ethermine.org:4444 \
-P stratum1+tcp://${ETHEREUM_ADDRESS}.%H@asia1.ethermine.org:4444
Restart=on-failure

[Install]
WantedBy=multi-user.target

EOF

# Disable variable expansion by quoting the label
# of the here-doc.
cat <<'EOF' > "/usr/local/bin/teamredminerctl"
#!/bin/bash
# Small helper script for interacting with the teamredminer
# Systemd unit.

case "$1" in
  start)
    sudo systemctl start teamredminer
    ;;
  stop)
    sudo systemctl stop teamredminer
    ;;
  status)
    sudo systemctl status teamredminer
    ;;
  log)
    # '--output cat' is used to restore colors.
    sudo journalctl -fu teamredminer --output cat
    ;;
esac

EOF

chmod a+x "/usr/local/bin/teamredminerctl"

create_plugin.py finish coinboot_$(basename $0)_${TEAMREDMINER_RELASE}_$(date +%Y%m%d.%H%M)
