---
name: build
on: [push, workflow_dispatch]
jobs:
  build_and_upload_artifacts:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup required packages for Coinbootmaker
        run: |
          sudo apt update
          sudo apt install --yes fakeroot bridge-utils
      # Coinboot plugins creation script have to be executable and we omit all upstream code directories
      - name: Build Coinboot plugins with Coinbootmaker
        run: |
          #for plugin in $(find src -executable -type f ! -path "*/upstream/*" | sed 's/src\///g'); do
          for plugin in teamredminer; do
            ./coinbootmaker -p $plugin
          done
      - name: List build artifacts
        run: ls -la build
      - name: Upload artifacts to object storage
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_ENDPOINT: https://s3.eu-central-1.wasabisys.com
          AWS_S3_BUCKET: coinboot
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'src'
