---
name: build
on: [push, workflow_dispatch]
jobs:
  build_and_upload_artifacts:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup required packages
        run: |
          sudo apt update
          sudo apt install --yes fakeroot bridge-utils pipenv
      - name: Install Python dependcies with pipenv
        run: pipenv install 
      # Coinboot plugins creation script have to be executable and we omit all upstream code directories
      - name: Build Coinboot plugins with Coinbootmaker and upload to object storage
        run: |
          #for plugin in $(find src -executable -type f ! -path "*/upstream/*" | sed 's/src\///g'); do
          for plugin in ethminer.yaml; do
            ./coinbootmaker_helper create $plugin
          done
      - name: Create README with list of available Coinboot plugins
        run: |
          ./coinbootmaker_helper create readme
          cat README.md
      - name: List build artifacts
        run: |
          ls -la build
          s3cmd --host=s3.wasabisys.com --host-bucket="%(bucket)s.s3.wasabisys.com" ls --recursive s3://coinboot/ | grep -oP '[^\/]+$'
    # Use https://github.com/marketplace/actions/dynamic-readme to generate dynamic list of available plugins in object storage
