---
name: build
on: [push, workflow_dispatch]
jobs:
  build_and_upload_artifacts:
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup required packages
        run: |
          sudo apt update
          sudo apt install --yes fakeroot bridge-utils pipenv
      - name: Set up yq - portable yaml processor
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.9.3/yq_linux_amd64 -O /usr/local/bin/yq &&\
          sudo chmod +x /usr/local/bin/yq
      - name: Install Python dependcies with pipenv
        run: pipenv install
      # Coinboot plugins creation script have to be executable and we omit all upstream code directories
      - name: Build Coinboot plugins with Coinbootmaker and upload to object storage
        run: |
          #for plugin in $(find src -executable -type f ! -path "*/upstream/*" | sed 's/src\///g'); do
          for plugin in src/ethminer.yaml; do
            pipenv run ./coinbootmaker_helper create plugin $plugin
          done
      - name: Create README with list of available Coinboot plugins
        run: |
          pipenv run ./coinbootmaker_helper create readme
          cat README.md
      - name: List build artifacts
        run: |
          ls -la build
    # Use https://github.com/marketplace/actions/dynamic-readme to generate dynamic list of available plugins in object storage
