---
name: build
on: [push, workflow_dispatch]
jobs:
  build_and_upload_artifacts:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.1
        with:
          provider: aws
          region: 'eu-central-1'
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Setup required packages for Coinbootmaker
        run: |
          sudo apt update
          sudo apt install --yes fakeroot bridge-utils
      # Coinboot plugins creation script have to be executable and we omit all upstream code directories
      - name: Build Coinboot plugins with Coinbootmaker and upload to object storage
        run: |
          #for plugin in $(find src -executable -type f ! -path "*/upstream/*" | sed 's/src\///g'); do
          for plugin in teamredminer; do
            ./coinbootmaker -p $plugin
            which s3cmd
            s3cmd --host=s3.wasabisys.com --host-bucket="%(bucket)s.s3.wasabisys.com" put --acl-public --recursive --exclude ".keep" build/ s3://coinboot
          done
      - name: List build artifacts
        run: |
          ls -la build
          s3cmd --host=s3.wasabisys.com --host-bucket="%(bucket)s.s3.wasabisys.com" ls --recursive s3://coinboot/ | grep -oP '[^\/]+$'
    # Use https://github.com/marketplace/actions/dynamic-readme to generate dynamic list of available plugins in object storage
