---
name: build
on: [push, workflow_dispatch]
jobs:
  build_and_upload_artifacts:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup required packages for Coinbootmaker
        run: |
          sudo apt update
          sudo apt install --yes fakeroot bridge-utils
      # Coinboot plugins creation script have to be executable and we omit all upstream code directories
      - name: Build Coinboot plugins with Coinbootmaker
        run: |
          #for plugin in $(find src -executable -type f ! -path "*/upstream/*" | sed 's/src\///g'); do
          for plugin in teamredminer; do
            ./coinbootmaker -p $plugin
          done
      - name: List build artifacts
        run: ls -la build
      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.1
        with:
          provider: aws # default is linode
          region: 'eu-central-1'
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload artifacts to object storage
        run: |
          s3cmd sync --recursive --acl-public dist s3://coinboot --host https://s3.eu-central-1.wasabisys.com ./build 
          s3cmd info s3://coinboot
